# Generated by Django 2.0.4 on 2018-09-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idagenda', models.AutoField(db_column='idAgenda', primary_key=True, serialize=False)),
                ('dataagenda', models.DateField(blank=True, db_column='dataAgenda', null=True)),
                ('horarioagenda', models.TimeField(blank=True, db_column='horarioAgenda', null=True)),
            ],
            options={
                'db_table': 'Agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('idcatalogo', models.AutoField(db_column='idCatalogo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Catalogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nomecliente', models.CharField(blank=True, db_column='nomeCliente', max_length=120, null=True)),
                ('assiduidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('idcor', models.AutoField(db_column='idCor', primary_key=True, serialize=False)),
                ('colorido', models.IntegerField(blank=True, null=True)),
                ('faixavalor', models.FloatField(blank=True, db_column='faixaValor', null=True)),
            ],
            options={
                'db_table': 'Cor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emailcliente',
            fields=[
                ('idemail', models.AutoField(db_column='idEmail', primary_key=True, serialize=False)),
                ('enderecoemail', models.CharField(blank=True, db_column='enderecoEmail', max_length=100, null=True)),
            ],
            options={
                'db_table': 'EmailCliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estilos',
            fields=[
                ('idestilo', models.AutoField(db_column='idEstilo', primary_key=True, serialize=False)),
                ('estilo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Estilos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('idimagem', models.AutoField(db_column='idImagem', primary_key=True, serialize=False)),
                ('urlimagem', models.CharField(blank=True, db_column='urlImagem', max_length=350, null=True)),
                ('ratins', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Imagens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('idportifolio', models.AutoField(db_column='idPortifolio', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Portifolio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('idregiao', models.AutoField(db_column='idRegiao', primary_key=True, serialize=False)),
                ('regiaodocorpo', models.CharField(blank=True, db_column='regiaoDoCorpo', max_length=50, null=True)),
                ('faixavalor', models.FloatField(blank=True, db_column='faixaValor', null=True)),
            ],
            options={
                'db_table': 'Regiao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('idservico', models.AutoField(db_column='idServico', primary_key=True, serialize=False)),
                ('servicodesconto', models.FloatField(blank=True, db_column='servicoDesconto', null=True)),
                ('servicofinalizado', models.IntegerField(blank=True, db_column='servicoFinalizado', null=True)),
            ],
            options={
                'db_table': 'Servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('idsessao', models.AutoField(db_column='idSessao', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Sessao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('idtamanho', models.AutoField(db_column='idTamanho', primary_key=True, serialize=False)),
                ('tamanho', models.CharField(blank=True, max_length=8, null=True)),
                ('faixavalor', models.FloatField(blank=True, db_column='faixaValor', null=True)),
            ],
            options={
                'db_table': 'Tamanho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tatuador',
            fields=[
                ('idtatuador', models.AutoField(db_column='idTatuador', primary_key=True, serialize=False)),
                ('nometatuador', models.CharField(blank=True, db_column='nomeTatuador', max_length=120, null=True)),
                ('apitokens', models.CharField(blank=True, db_column='apiTokens', max_length=350, null=True)),
            ],
            options={
                'db_table': 'Tatuador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefonecliente',
            fields=[
                ('idtelefone', models.AutoField(db_column='idTelefone', primary_key=True, serialize=False)),
                ('numerotelefone', models.CharField(blank=True, db_column='numeroTelefone', max_length=15, null=True)),
            ],
            options={
                'db_table': 'TelefoneCliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('loginusuario', models.CharField(blank=True, db_column='loginUsuario', max_length=120, null=True)),
                ('senhausuario', models.CharField(blank=True, db_column='senhaUsuario', max_length=300, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=2, null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
    ]
