# Generated by Django 2.0.8 on 2018-11-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apitoken',
            fields=[
                ('idapitokens', models.AutoField(db_column='idApiTokens', primary_key=True, serialize=False)),
                ('nomeapi', models.CharField(blank=True, db_column='nomeApi', max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'db_table': 'apiToken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('idestilo', models.AutoField(db_column='idEstilo', primary_key=True, serialize=False)),
                ('estilo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Estilo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('idimagem', models.AutoField(db_column='idImagem', primary_key=True, serialize=False)),
                ('urlimagem', models.CharField(db_column='urlImagem', max_length=255, unique=True)),
                ('ratins', models.IntegerField()),
                ('fonteimagem', models.IntegerField(db_column='fonteImagem')),
            ],
            options={
                'db_table': 'Imagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagemtag',
            fields=[
                ('idimagemtag', models.AutoField(db_column='idImagemTag', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ImagemTag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('idservico', models.AutoField(db_column='idServico', primary_key=True, serialize=False)),
                ('servicodesconto', models.FloatField(blank=True, db_column='servicoDesconto', null=True)),
                ('servicofinalizado', models.IntegerField(blank=True, db_column='servicoFinalizado', null=True)),
            ],
            options={
                'db_table': 'Servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('idtag', models.AutoField(db_column='idTag', primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('idtoken', models.AutoField(db_column='idToken', primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=350)),
                ('tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'Token',
                'managed': False,
            },
        ),
    ]
