# Generated by Django 2.0.8 on 2018-11-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apitoken_estilo_imagem_imagemtag_servico_tag_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('idpromo', models.AutoField(db_column='idPromo', primary_key=True, serialize=False)),
                ('desconto', models.FloatField(db_column='desconto')),
                ('ativo', models.IntegerField(db_column='ativo')),
            ],
            options={
                'db_table': 'Promocao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PromoImagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField(db_column='ativo')),
            ],
            options={
                'db_table': 'PromoImagem',
                'managed': False,
            },
        ),
    ]
